package com.seazonechallenge.desafio.service.exceptions;

public class ResourceNotFoundException extends RuntimeException {

    public ResourceNotFoundException(int id) {
        super("NÃ£o existe registro com o id " + id + ". Verifique e tente novamente.");
    }

}
